services:
  db:
    image: postgres:17
    container_name: tylstrup-db
    restart: always
    environment:
      POSTGRES_USER: tylstrup
      POSTGRES_PASSWORD: tylstrup-appen
      POSTGRES_DB: tylstrup
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  s3:
    image: minio/minio:latest
    container_name: tylstrup-s3
    command: server /data
    environment:
      MINIO_ROOT_USER: tylstrup
      MINIO_ROOT_PASSWORD: tylstrup-appen
    ports:
      - "9000:9000"
      - "9001:9001" # Console UI
    volumes:
      - s3_data:/data
  s3-mc:
    image: minio/mc
    container_name: tylstrup-s3-mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 tylstrup tylstrup-appen &&
      mc mb local/bucket ||
      echo 'Bucket already exists' &&
      mc policy set public local/bucket
      "
    restart: "no"
volumes:
  db_data:
  s3_data:
    