services:
  db:
    container_name: landsby-db
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    environment:
      POSTGRES_USER: landsby
      POSTGRES_PASSWORD: landsby-appen
      POSTGRES_DB: landsby
      LANG: da_DK.UTF-8
      LC_COLLATE: da_DK.UTF-8
      LC_CTYPE: da_DK.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  s3:
    image: minio/minio:latest
    container_name: landsby-s3
    command: server /data
    environment:
      MINIO_ROOT_USER: landsby
      MINIO_ROOT_PASSWORD: landsby-appen
    ports:
      - "9000:9000"
      - "9001:9001" # Console UI
    volumes:
      - s3_data:/data
  s3-mc:
    image: minio/mc
    container_name: landsby-s3-mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 landsby landsby-appen &&
      mc mb local/bucket ||
      echo 'Bucket already exists' &&
      mc policy set public local/bucket
      "
    restart: "no"
volumes:
  db_data:
  s3_data:
    