export const t = {
  login: "Log ind",
  logout: "Log ud",
  microsoft: "Microsoft",
  google: "Google",
  facebook: "Facebook",
  title: "Titel",
  location: "Lokation",
  start: "Start",
  end: "Slut",
  durationHours: "Varighed (timer)",
  description: "Beskrivelse",
  save: "Gem",
  create: "Opret",
  terms: "Betingelser for brug",
  privacy: "Privatlivspolitik og GDPR",
  support: "Support",
  name: "Navn",
  vatId: "CVR",
  town: "By",
  towns: "Byer",
  noRoles: "Ingen roller",
  noSubscriptions: "Ingen byer valgt",
  back: "Tilbage",
  organization: "Organisation",
  myTown: "Min by",
  profile: "Profil",
  createOrganization: "Opret organisation",
  roles: "Roller",
  email: "E-mail",
  me: "Mig (personlig)",
  myProfile: "Min profil",
  myOrganization: "Min organisation",
  signinAgreeTerms: "Ved login accepterer du vores ",
  address: "Adresse",
  postCode: "Postnr.",
  phone: "Tlf.",
  isCharity: "Forening",
  yes: "Ja",
  no: "Nej",
  createEvent: "Opret begivenhed",
  editEvent: "Rediger begivenhed",
  createPost: "Opret opslag",
  upload: "Upload",
  welcome: "Velkommen!",
  heroTitle: [
    "Velkommen til",
    "Landsbyen!"
  ],
  heroSubTitle: "Følg med i, hvad der sker i din by!",
  chooseTowns: "Vælg en eller flere byer at følge",
  chooseMunicipality: "Vælg kommune",
  choose: "Vælg",
  addTown: "Tilføj by",
  add: "Tilføj",
  getGoing: "Kom igang!",
  pickAlbum: "Vælg fra album ...",
  endMustBeLaterThanStart: "Slut skal være senere end starttidspunktet.",
  required: "Påkrævet",
  mustBeFuture: "Skal være i fremtiden",
  mustBeNonZero: "Skal være større end 0.",
  mustBeLessTwoDays: "Skal være mindre end 48 timer.",
  delete: "Slet",
  images: "Billeder",
  image: "Billede",
  coverImage: "Cover billede",
  phoneFormat: "Telefon skal være 8 cifre med evt. +45 foran",
  presentation: "Præsentation",
  presentationImages: "Billeder til præsentation",
  municipality: "Kommune",
  copyright: ({ year }: { year: string }) => `Copyright(C) ${year}, Kimatik`,
};
