export const t = {
  login: "Log ind",
  logout: "Log ud",
  microsoft: "Microsoft",
  google: "Google",
  facebook: "Facebook",
  title: "Titel",
  location: "Lokation",
  start: "Start",
  end: "Slut",
  description: "Beskrivelse",
  save: "Gem",
  create: "Opret",
  terms: "Betingelser for brug",
  privacy: "Privatlivspolitik og GDPR",
  support: "Support",
  name: "Navn",
  vatId: "CVR",
  town: "By",
  back: "Tilbage",
  organization: "Organisation",
  signinAgreeTerms: "Ved login accepterer du vores ",
  copyright: ({ year }: { year: string }) =>
    `Copyright(C) ${year}, Landsbytavlen.dk`,
};
